import mongoose , {Schema} from "mongoose" ;

 const userSchema  = new Schema(
    {
        username : {
            type : String , 
            required : true , 
            unique : true , 
            lowercase : true , 
            trim : true ,
            index: true 
        } ,
        email : {
            type : String , 
            required : ture , 
            unique : true , 
            lowercase : true , 
            trim : true , 
        } ,
        fullname : {
            type : String , 
            required : ture , 
            trim : true , 
            index : true
        } ,
        avatar : { 
            type : String , //cloudnary url
            required : true , 
        },
        coverImage : { 
            type : String , //cloudnary yr
        },
        watchHistory : [
            {
                type : Schema.Type.ObjectId ,
                ref : "Video"
            }
        ] ,
        password : {
            type : String ,
            required : [true , "Password is Required"]
        } ,
        refreshToken : {
            type : String
        }
} , { timestamps : true }
)

 export  const User = mongoose.model("User" , userSchema)

// inside the user we also have to store the watch history
//  it is an array that consists -- video id = which are also generated by mongoDB

// pa